name: Check JSON Format
on:
  push:
    branches-ignore:
      - main
jobs:
  check-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate JSON
        run: |
          if ! jq empty quotes.json; then
            echo "quotes.json is not valid JSON"
            exit 1
          fi
          echo "quotes.json is valid JSON"